apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  labels:
    example: auth
type: Opaque
data:
  request.username: bXl1c2Vy
  request.password: bXlwYXNz
---
apiVersion: httpd.apache.org/v1alpha1
kind: ApacheBench
metadata:
  name: example-apache-bench
  labels:
    example: auth
spec:
  authenticate: true
  secretName: example-secret
  url: http://httpd.apache.org/
