apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-bench-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apache-bench-operator
  template:
    metadata:
      labels:
        name: apache-bench-operator
    spec:
      serviceAccountName: apache-bench-operator
      containers:
        - name: apache-bench-operator
          image: quay.io/jmckind/apache-bench-operator@sha256:b02d948c0819c2ce9e2d5d16158147e4e475d13eb0229c02d6b675ee10c44a6e
          command:
          - apache-bench-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apache-bench-operator"
          resources: {}
